### PR TITLE
Metric tracking missed proposals

### PR DESCRIPTION
**Pull request by wojtek-coreum**
---

#### PR checklist

- [ ] Tests written/updated
- [ ] Changelog entry added in `.changelog` (we use [unclog](https://github.com/informalsystems/unclog) to manage our changelog)
- [ ] Updated relevant documentation (`docs/` or `spec/`) and code comments
- [ ] Title follows the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) spec

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/cometbft/1)

### CODE REVIEW

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/cometbft/1)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`consensus/state.go` line 1862 at r1](https://reviewable.io/reviews/coreumfoundation/cometbft/1#-Ny-aPkr35yePo65T9kW:-Ny-aPkr35yePo65T9kX:b89ucy5) ([raw file](https://github.com/coreumfoundation/cometbft/blob/ca77193b06f94f4737035f7e9db6f7f970b7d81a/consensus/state.go#L1862)):*
> ```Go
> 
> 	var expectedProposerValue float64
> 	if bytes.Equal(cs.RoundState.Validators.Proposer.Address.Bytes(), cs.state.Validators.Proposer.Address.Bytes()) {
> ```

Can't you use 2 counters?
1st - count the proposers who propose the block.
2nd - count the proposers who miss the block. 

Using this you will be able to divide one value by another and get the missing rate. 
___
*[`consensus/state.go` line 1865 at r1](https://reviewable.io/reviews/coreumfoundation/cometbft/1#-Ny-XoiU8bVwHYdfpCG1:-Ny-XoiU8bVwHYdfpCG2:bhprvgf) ([raw file](https://github.com/coreumfoundation/cometbft/blob/ca77193b06f94f4737035f7e9db6f7f970b7d81a/consensus/state.go#L1865)):*
> ```Go
> 		expectedProposerValue = 1.0
> 	}
> 	cs.metrics.ExpectedProposers.With("validator_address", cs.state.Validators.Proposer.Address.String()).Observe(expectedProposerValue)
> ```

The "validator_address" should be a shared constant.

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/cometbft/1)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`consensus/state.go` line 1862 at r1](https://reviewable.io/reviews/coreumfoundation/cometbft/1#-Ny-aPkr35yePo65T9kW:-Ny-kdbd3TmkJXxD8xLU:bq558ta) ([raw file](https://github.com/coreumfoundation/cometbft/blob/ca77193b06f94f4737035f7e9db6f7f970b7d81a/consensus/state.go#L1862)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Can't you use 2 counters?
1st - count the proposers who propose the block.
2nd - count the proposers who miss the block. 

Using this you will be able to divide one value by another and get the missing rate.
</blockquote></details>

yes, that's what `Summary` metric type is for. I need to check if it's possible to use it.
___
*[`consensus/state.go` line 1865 at r1](https://reviewable.io/reviews/coreumfoundation/cometbft/1#-Ny-XoiU8bVwHYdfpCG1:-Ny-kTY79HyBwEuQBUYt:b2uheu9) ([raw file](https://github.com/coreumfoundation/cometbft/blob/ca77193b06f94f4737035f7e9db6f7f970b7d81a/consensus/state.go#L1865)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

The "validator_address" should be a shared constant.
</blockquote></details>

It is commmonly used in other metrics too. Do you want me to use the constant everywhere? Not sure if improving cometBFT source code is a good idea

**Review by dzmitryhil — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/cometbft/1#-:-Ny0Aqr35ob6NI14x7SW:bnfp4nl)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @miladz68 and @ysv)

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/cometbft/1)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`consensus/state.go` line 1862 at r1](https://reviewable.io/reviews/coreumfoundation/cometbft/1#-Ny-aPkr35yePo65T9kW:-Ny4MTDaDJ9A5PoaXbPi:bb6un1j) ([raw file](https://github.com/coreumfoundation/cometbft/blob/ca77193b06f94f4737035f7e9db6f7f970b7d81a/consensus/state.go#L1862)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

yes, that's what `Summary` metric type is for. I need to check if it's possible to use it.
</blockquote></details>

Done

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/cometbft/1)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`consensus/state.go` line 1862 at r1](https://reviewable.io/reviews/coreumfoundation/cometbft/1#-Ny-aPkr35yePo65T9kW:-Ny4vo6x1nHNOMAK3nMq:b3g0pr2) ([raw file](https://github.com/coreumfoundation/cometbft/blob/ca77193b06f94f4737035f7e9db6f7f970b7d81a/consensus/state.go#L1862)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Done
</blockquote></details>

My ides was a bit different use `Counter` and count both validators who propose and who miss. You can even use the same counter but with 2 tags/labels `validator_address`, `missed (true/false)`
___
*[`consensus/state.go` line 1862 at r2](https://reviewable.io/reviews/coreumfoundation/cometbft/1#-Ny4vgoH1fQCwX3gbgX9:-Ny4vgoH1fQCwX3gbgXA:bbkohfp) ([raw file](https://github.com/coreumfoundation/cometbft/blob/1dbb24c1662556f732b15c311a7beab711cb180d/consensus/state.go#L1862)):*
> ```Go
> 
> 	var expectedProposerValue float64
> 	if bytes.Equal(cs.RoundState.Validators.Proposer.Address.Bytes(), cs.state.Validators.Proposer.Address.Bytes()) {
> ```

What if there were 3 rounds? Will it still work?

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/cometbft/1)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`consensus/state.go` line 1862 at r1](https://reviewable.io/reviews/coreumfoundation/cometbft/1#-Ny-aPkr35yePo65T9kW:-Ny50HaFCihb7MW9nUYu:bb5x5jh) ([raw file](https://github.com/coreumfoundation/cometbft/blob/ca77193b06f94f4737035f7e9db6f7f970b7d81a/consensus/state.go#L1862)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

My ides was a bit different use `Counter` and count both validators who propose and who miss. You can even use the same counter but with 2 tags/labels `validator_address`, `missed (true/false)`
</blockquote></details>

But this is what Summary is for by definition
___
*[`consensus/state.go` line 1862 at r2](https://reviewable.io/reviews/coreumfoundation/cometbft/1#-Ny4vgoH1fQCwX3gbgX9:-Ny50N6W-Gl7pXdcE54Q:b-3tye2w) ([raw file](https://github.com/coreumfoundation/cometbft/blob/1dbb24c1662556f732b15c311a7beab711cb180d/consensus/state.go#L1862)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

What if there were 3 rounds? Will it still work?
</blockquote></details>

Yes, because metrics are calculated when block is committed.

**Review by dzmitryhil — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/cometbft/1)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @miladz68 and @ysv)

**Review by ysv — DISMISSED** [review]
> Reviewed 1 of 3 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/cometbft/1)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68 and @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/cometbft/1#-NyKQu0i0SL8V8q4Cfap:-NyKQu0i0SL8V8q4Cfaq:bq7uqbc) (no related file):*
IMO as the next step we can test this implementation on our mainnet. Especially on blocks which had multiple rounds 

___
___
*[`consensus/metrics.go` line 118 at r2](https://reviewable.io/reviews/coreumfoundation/cometbft/1#-NyKPxTt4IivJaPRKIzX:-NyKPxTu3cHAGSfEvupt:b8xwuva) ([raw file](https://github.com/coreumfoundation/cometbft/blob/1dbb24c1662556f732b15c311a7beab711cb180d/consensus/metrics.go#L118)):*
> ```Go
> 	LateVotes metrics.Counter `metrics_labels:"vote_type"`
> 
> 	// ExpectedProposers verifies that expected proposer really proposed the block.
> ```

nit: WDYM by `verifies that expected proposer really proposed the block` ?

do you mean that this metric `shows if actual proposer is equal to expected ` ?

I suggest to rephrase it



_Code quote:_
```Go
verifies that expected proposer really proposed the block.
```

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/cometbft/1)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @miladz68 and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/cometbft/1#-NyKQu0i0SL8V8q4Cfap:-NyKqKPs4G8wDDx-V51W:b-nfhxb4) (no related file):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

IMO as the next step we can test this implementation on our mainnet. Especially on blocks which had multiple rounds
</blockquote></details>

That's the plan

___
___
*[`consensus/metrics.go` line 118 at r2](https://reviewable.io/reviews/coreumfoundation/cometbft/1#-NyKPxTt4IivJaPRKIzX:-NyKqxuv1Ouo2HQjJ21s:bb6un1j) ([raw file](https://github.com/coreumfoundation/cometbft/blob/1dbb24c1662556f732b15c311a7beab711cb180d/consensus/metrics.go#L118)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

nit: WDYM by `verifies that expected proposer really proposed the block` ?

do you mean that this metric `shows if actual proposer is equal to expected ` ?

I suggest to rephrase it
</blockquote></details>

Done

**Review by ysv — DISMISSED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/cometbft/1)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @miladz68)

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 1 of 3 files at r1, 1 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/cometbft/1)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68 and @wojtek-coreum)

___
*[`scripts/metricsgen/metricsgen.go` line 114 at r3](https://reviewable.io/reviews/coreumfoundation/cometbft/1#-NyQ_vVV6d9UCpE50XLe:-NyQ_vVV6d9UCpE50XLf:b-ro4p2z) ([raw file](https://github.com/coreumfoundation/cometbft/blob/920cba47decd1e37557e90ceb936e13979a28c04/scripts/metricsgen/metricsgen.go#L114)):*
> ```Go
> type ParsedMetricField struct {
> 	TypeName       string
> 	MetricTypeName string
> ```

BTW why don't you call it MetricType ?

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/cometbft/1)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @miladz68)

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/cometbft/1)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @miladz68)

**Pull request merged**
